(function () {
  var KEY = "minikyumons_save_v4_title_eggs"; var BACKUP_KEY = "minikyumons_save_backup"; var SAVE_VERSION = 3;
  var state; var parallaxOffset = 0; var autonomousTimer = null; var selected = 0; var statusOpen = false; var menuOpen = true; var submenu = null; var submenuSelected = 0; var introOpen = false; var titleOpen = false; var eggOpen = false; var hatchInYard = false; var hatchTimer = null; var titleSelected = 0; var eggSelected = 0; var eggSpecies = ["Água", "Planta", "Fogo"]; var introSpecies = "Água"; var lastTick = new Date().getTime(); var toastTimer; var idleFrame = 0; var idleBlink = 0; var animationTimer = null; var animationToken = 0;
  var actions = [{id:"feed", icon:"●", label:"Alimentar"}, {id:"play", icon:"✦", label:"Brincar"}, {id:"clean", icon:"≈", label:"Limpar"}, {id:"pet", icon:"♡", label:"Carinho"}, {id:"sleep", icon:"z", label:"Dormir"}, {id:"new", icon:"+", label:"Novo ovo"}]; var feedOptions = [{id:"snack", icon:"·", label:"Lanche"}, {id:"meal", icon:"●", label:"Comida"}, {id:"water", icon:"≈", label:"Água"}]; var playOptions = [{id:"walk", icon:"→", label:"Passear"}, {id:"dance", icon:"✦", label:"Dançar"}, {id:"train", icon:"◆", label:"Treinar"}]; var sleepOptions = [{id:"quick", icon:"z", label:"Soneca rápida"}, {id:"nap", icon:"Z", label:"Soneca"}, {id:"deep", icon:"✦", label:"Sono profundo"}];
  function clamp(v) { return Math.max(0, Math.min(100, Math.round(v * 10) / 10)); }
  function applyTimeOfDay() { var h = new Date().getHours(); var home = document.getElementById("home-view"); if (!home) { return; } home.className = home.className.replace(/\btime-(morning|afternoon|night)\b/g, ""); if (h >= 6 && h < 12) { home.className += " time-morning"; } else if (h >= 12 && h < 18) { home.className += " time-afternoon"; } else { home.className += " time-night"; } home.className += " parallax-active"; } function parallaxShift(dir) { parallaxOffset += dir * 8; if (parallaxOffset > 22) { parallaxOffset = 22; } if (parallaxOffset < -22) { parallaxOffset = -22; } var image = document.getElementById("yard-image"); if (image) { image.style.transform = "translateX(" + parallaxOffset + "px) scale(1.06)"; } var cloudA = document.querySelector(".cloud.a"); var cloudB = document.querySelector(".cloud.b"); if (cloudA) { cloudA.style.marginLeft = (parallaxOffset * .35) + "px"; } if (cloudB) { cloudB.style.marginRight = (-parallaxOffset * .22) + "px"; } } function now() { var d = new Date(); var h = String(d.getHours()); var m = String(d.getMinutes()); if (h.length < 2) { h = "0" + h; } if (m.length < 2) { m = "0" + m; } return h + ":" + m; }
  function newPet(name, species) { return {version:SAVE_VERSION, name:name || "Kyu", species:species || "Ãgua", hunger:78, energy:74, happiness:82, hygiene:68, health:96, bond:0, care:0, xp:0, level:1, stage:"BebÃª", expression:"neutral", memories:["O ovo chegou a um lugar seguro."], dirt:0, poop:0, personality:{carinhoso:0, curioso:0, brincalhao:0}, routine:{lastAction:"hatch", streak:0, lastDay:""}, milestones:[], started:false, lastSeen:new Date().getTime()}; }
  function normalizeState() { if (!state || typeof state !== "object") { state = newPet("Kyu", "Água"); } if (!state.name) { state.name = "Kyu"; } if (!state.species || ["Água","Planta","Fogo"].indexOf(state.species) < 0) { state.species = "Água"; } if (!state.memories || !(state.memories instanceof Array)) { state.memories = []; } if (typeof state.dirt !== "number") { state.dirt = 0; } if (typeof state.poop !== "number") { state.poop = 0; } if (typeof state.bond !== "number") { state.bond = 0; } if (typeof state.care !== "number") { state.care = 0; } if (!state.personality || typeof state.personality !== "object") { state.personality = {carinhoso:0, curioso:0, brincalhao:0}; } if (typeof state.personality.carinhoso !== "number") { state.personality.carinhoso = 0; } if (typeof state.personality.curioso !== "number") { state.personality.curioso = 0; } if (typeof state.personality.brincalhao !== "number") { state.personality.brincalhao = 0; } if (!state.routine || typeof state.routine !== "object") { state.routine = {lastAction:"hatch", streak:0, lastDay:""}; } if (typeof state.routine.streak !== "number") { state.routine.streak = 0; } if (!state.milestones || !(state.milestones instanceof Array)) { state.milestones = []; } if (!state.expression || (state.expression !== "sleep" && state.expression !== "neutral")) { state.expression = "neutral"; } if (state.species === "Bubblum") { state.species = "Água"; }     if (typeof state.xp !== "number") { state.xp = (typeof state.bond === "number" ? state.bond * 5 : 0); if (state.stage === "Jovem") { state.xp = Math.max(state.xp, xpForLevel(10)); } if (state.stage === "Companheiro") { state.xp = Math.max(state.xp, xpForLevel(20)); } }
    if (typeof state.level !== "number" || state.level < 1) { state.level = 1; }
    if (state.level > 30) { state.level = 30; }
    syncGrowth(false);    state.version = SAVE_VERSION; } function load() { var raw = null; try { raw = localStorage.getItem(KEY); } catch (e) {} if (raw) { try { state = JSON.parse(raw); } catch (e2) { state = null; } } if (!state) { try { raw = localStorage.getItem(BACKUP_KEY); if (raw) { state = JSON.parse(raw); } } catch (e3) { state = null; } } if (!state) { state = newPet("Kyu", "Água"); } normalizeState(); titleOpen = true; offline(); save(); }
  function offline() { var t = new Date().getTime(); var hours = (t - (state.lastSeen || t)) / 3600000; if (hours < 0) { hours = 0; } hours = Math.min(hours, 12); if (hours > .02 && state.started !== false) { state.hunger = clamp(state.hunger - hours * 3.6); state.energy = clamp(state.energy - hours * 2.2); state.happiness = clamp(state.happiness - hours * 1.6); state.hygiene = clamp(state.hygiene - hours * 2.0); state.dirt = clamp(state.dirt + hours * .35); var balance = Math.min(state.hunger, state.energy, state.happiness, state.hygiene); if (balance > 48) { state.health = clamp(state.health + hours * .45); } else if (balance < 18) { state.health = clamp(state.health - hours * .15); } if (hours > .5 && state.memories.indexOf("Ele passou um tempo tranquilo esperando por você.") < 0) { memory("Ele passou um tempo tranquilo esperando por você."); } } state.lastSeen = t; }
  function save() { state.lastSeen = new Date().getTime();     if (typeof state.xp !== "number") { state.xp = (typeof state.bond === "number" ? state.bond * 5 : 0); if (state.stage === "Jovem") { state.xp = Math.max(state.xp, xpForLevel(10)); } if (state.stage === "Companheiro") { state.xp = Math.max(state.xp, xpForLevel(20)); } }
    if (typeof state.level !== "number" || state.level < 1) { state.level = 1; }
    if (state.level > 30) { state.level = 30; }
    syncGrowth(false);    state.version = SAVE_VERSION; try { var serialized = JSON.stringify(state); var previous = localStorage.getItem(KEY); if (previous && previous !== serialized) { localStorage.setItem(BACKUP_KEY, previous); } localStorage.setItem(KEY, serialized); } catch (e) {} }
  function memory(text) { state.memories.unshift(text); if (state.memories.length > 5) { state.memories.length = 5; } } function recordAction(actionName) { var day = new Date().getFullYear() + "-" + new Date().getMonth() + "-" + new Date().getDate(); if (!state.routine) { state.routine = {lastAction:"", streak:0, lastDay:""}; } if (state.routine.lastDay !== day) { state.routine.streak = state.routine.lastDay ? state.routine.streak + 1 : 1; state.routine.lastDay = day; } state.routine.lastAction = actionName; if (!state.personality) { state.personality = {carinhoso:0, curioso:0, brincalhao:0}; } if (actionName === "pet" || actionName === "snack") { state.personality.carinhoso = clamp(state.personality.carinhoso + 2); } if (actionName === "dance" || actionName === "train") { state.personality.brincalhao = clamp(state.personality.brincalhao + (actionName === "dance" ? 3 : 1)); } if (actionName === "walk" || actionName === "water" || actionName === "train") { state.personality.curioso = clamp(state.personality.curioso + (actionName === "walk" ? 2 : 1)); } } function xpForLevel(level) { return Math.max(0, (level - 1) * 18); }
  function growthStageForLevel(level) { return level >= 20 ? "Companheiro" : (level >= 10 ? "Jovem" : "BebÃª"); }
  function growthScale() { var level = state.level || 1; var start = level >= 20 ? 20 : (level >= 10 ? 10 : 1); var end = level >= 20 ? 30 : (level >= 10 ? 19 : 9); var progress = end === start ? 1 : (level - start) / (end - start); return 0.72 + Math.min(1, Math.max(0, progress)) * 0.30; }
  function syncGrowth(showToast) { if (!state) { return; } var previousLevel = state.level || 1; if (state.xp < 0) { state.xp = 0; } while (state.level < 30 && state.xp >= xpForLevel(state.level + 1)) { state.level++; } var oldStage = state.stage; state.stage = growthStageForLevel(state.level); if (showToast && state.level > previousLevel) { memory(state.name + " alcanÃ§ou o nÃ­vel " + state.level + "."); toast("NÃ­vel " + state.level + " alcanÃ§ado!"); } if (state.stage !== oldStage) { memory(state.name + " entrou no estÃ¡gio " + state.stage + "."); toast("Novo estÃ¡gio: " + state.stage + "!"); } }
  function addExperience(amount) { state.xp = (state.xp || 0) + Math.max(0, amount || 0); syncGrowth(true); }
  function bond(n) { var amount = Math.max(0, n || 0); state.bond += amount; addExperience(amount * 5); }
  function submenuItems() { if (submenu === "feed") { return feedOptions; } if (submenu === "play") { return playOptions; } return sleepOptions; }
  function openSubmenu(id) { submenu = id; submenuSelected = 0; menuOpen = true; renderCarousel(); renderMenuState(); toast(id === "feed" ? "Escolha o que oferecer." : (id === "play" ? "Escolha uma brincadeira." : "Escolha como descansar.")); }
  function performFeed(option) { if (option === "snack") { state.hunger = clamp(state.hunger + 8); state.happiness = clamp(state.happiness + 3); state.poop = clamp(state.poop + 5); memory(state.name + " recebeu um lanchinho."); toast("Lanche servido."); } else if (option === "meal") { state.hunger = clamp(state.hunger + 25); state.happiness = clamp(state.happiness + 4); state.poop = clamp(state.poop + 18); memory(state.name + " recebeu uma comida completa."); toast("Comida servida."); } else { state.hunger = clamp(state.hunger + 2); state.hygiene = clamp(state.hygiene + 3); state.health = clamp(state.health + 1); memory(state.name + " bebeu Ã¡gua fresca."); toast("Ãgua fresquinha."); } state.care++; recordAction(option); bond(1); submenu = null; save(); render(); playSequence("eating", true, returnToIdle, 2); react("bounce"); }
  function performPlay(option) { if (state.energy <= 12) { refuse("Estou cansadinho. Vamos descansar primeiro?"); return; } spawnParticles("play"); setExpression("happy", false); if (option === "walk") { state.happiness = clamp(state.happiness + 9); state.energy = clamp(state.energy - 3); state.hunger = clamp(state.hunger - 2); memory(state.name + " saiu para passear."); toast("Passeio tranquilo."); } else if (option === "dance") { state.happiness = clamp(state.happiness + 15); state.energy = clamp(state.energy - 6); state.hunger = clamp(state.hunger - 3); state.hygiene = clamp(state.hygiene - 2); memory(state.name + " danÃ§ou com vocÃª."); toast("Que danÃ§a divertida."); } else { state.happiness = clamp(state.happiness + 11); state.energy = clamp(state.energy - 8); state.hunger = clamp(state.hunger - 3); memory(state.name + " treinou uma nova brincadeira."); toast("Treino concluÃ­do."); } state.hygiene = clamp(state.hygiene - 1); state.care++; recordAction(option); bond(2); submenu = null; save(); render(); playSequence("play", true, returnToIdle, 2); react("shake"); }
  function performSleep(option) { if (state.energy >= 96) { refuse("Ainda estou descansado. Quero ficar acordado mais um pouco."); return; } var gain = option === "quick" ? 16 : (option === "nap" ? 34 : 55); state.energy = clamp(state.energy + gain); state.health = clamp(state.health + (option === "deep" ? 7 : 4)); state.hunger = clamp(state.hunger - (option === "deep" ? 4 : 2)); state.happiness = clamp(state.happiness + 2); state.care++; recordAction("sleep_" + option); bond(1); memory(state.name + " descansou com tranquilidade."); toast("Descanso concluÃ­do."); submenu = null; save(); render(); playSequence("sleep", true); react("bounce"); }
  function refuse(message) { state.happiness = clamp(state.happiness + 1); state.health = clamp(state.health + 1); toast(message || "Agora nÃ£o, mas estÃ¡ tudo bem."); memory(state.name + " recebeu um limite gentil."); save(); render(); }
  function setExpression(expr, hold) { state.expression = expr || "neutral"; render(); if (!hold && state.expression !== "sleep") { window.setTimeout(function () { if (!animationTimer) { state.expression = "neutral"; render(); } }, 1800); } }
  function action(id) { if (id === "new") { openNew(); return; } if (id === "feed") { openSubmenu("feed"); return; } if (id === "play") { openSubmenu("play"); return; } if (id === "clean") { if (state.hygiene >= 94 && state.dirt < 10 && state.poop < 10) { refuse("Estou limpinho. Obrigado por conferir!"); return; } spawnParticles("clean"); setExpression("happy", false); state.hygiene = clamp(state.hygiene + 30); state.dirt = 0; state.poop = 0; state.happiness = clamp(state.happiness + 7); state.health = clamp(state.health + 5); bond(1); state.care++; recordAction("clean"); memory(state.name + " ficou limpinho."); toast("Tudo limpo e aconchegante."); save(); render(); playSequence("clean", true, returnToIdle, 2); react("wiggle"); return; } if (id === "pet") { spawnParticles("pet"); setExpression("happy", false); state.happiness = clamp(state.happiness + 11); state.energy = clamp(state.energy + 1); state.health = clamp(state.health + 2); bond(2); state.care++; recordAction("pet"); memory(state.name + " ganhou um carinho especial."); toast("Ele adorou o carinho."); save(); render(); playSequence("pet", true, returnToIdle, 2); react("nod"); return; } if (id === "sleep") { openSubmenu("sleep"); return; } }
  function assetExpression() { if (state.species === "Ãgua") { return "idle-01"; } if (state.species === "Planta") { if (state.expression === "eating") { return "eating"; } if (state.expression === "sleep") { return "sleep"; } if (state.expression === "happy") { return "happy"; } if (state.expression === "sad") { return "sad"; } return "neutral"; } if (state.stage === "Jovem") { if (state.expression === "eating") { return "fire_stage2_eating"; } if (state.expression === "sleep") { return "fire_stage2_sleep"; } if (state.expression === "happy") { return "fire_stage2_happy"; } if (state.expression === "sad") { return "fire_stage2_sad"; } if (state.expression === "nice") { return "fire_stage2_nice"; } return "fire_stage2_neutral"; } if (state.expression === "eating") { return "eating"; } if (state.expression === "sleep") { return "sleep"; } if (state.expression === "happy") { return "happy"; } if (state.expression === "sad") { return "base"; } if (state.expression === "nice") { return "affection"; } return "base"; }
  function assetFolder() { if (state.species === "Ãgua") { return "animations64/water"; } if ((state.species === "Fogo" || state.species === "Nuvini") && state.stage === "Jovem") { return "fire_stage2"; } if (state.species === "Fogo" || state.species === "Nuvini") { return "fire_fixed64"; } if (state.species === "Planta") { return "plant64"; } return "animations64/water"; }
  function animationFolder() {
    if (state.species === "Fogo" || state.species === "Nuvini") { return "fire"; }
    if (state.species === "Planta") { return "plant"; }
    return "water";
  }
  function returnToIdle() { if (animationTimer) { window.clearTimeout(animationTimer); animationTimer = null; } if (state.expression !== "sleep") { state.expression = "neutral"; save(); render(); playSequence("idle", true); } } function playSequence(name, loop, done, repeatCount) { var asset = document.getElementById("pet-asset"); if (!asset || statusOpen) { return; } if (animationTimer) { window.clearTimeout(animationTimer); } var token = ++animationToken; var frame = 1; var cycles = 0; var total = name === "idle" ? 15 : (name === "sleep" ? 6 : (name === "eating" ? 5 : 3)); var delay = name === "sleep" ? 380 : (name === "idle" ? 250 : (name === "eating" ? 170 : 145)); function step() { if (token !== animationToken || statusOpen) { return; } asset.src = "assets/animations64/" + animationFolder() + "/" + name + "-" + (frame < 10 ? "0" + frame : frame) + ".png"; frame++; if (frame > total) { if (loop) { cycles++; frame = 1; if (repeatCount && cycles >= repeatCount) { if (done) { animationTimer = window.setTimeout(done, 120); } return; } if (name === "idle" && cycles >= 2) { cycles = 0; animationTimer = window.setTimeout(step, 360); } else { animationTimer = window.setTimeout(step, delay); } } else if (done) { done(); } return; } animationTimer = window.setTimeout(step, delay); } step(); }
  function idleStep() { if (statusOpen || state.expression !== "neutral" || animationTimer) { return; } playSequence("idle", true); }
  function react(kind) { var el = document.getElementById("pet-placeholder"); el.className = "pet-placeholder asset-mode " + kind; window.setTimeout(function () { el.className = "pet-placeholder asset-mode"; }, 650); } function showEmotion(type) { var el = document.getElementById("emotion-overlay"); if (!el) { return; } var symbols = {sparkle:"✦", heart:"♥", tears:"• •", curious:"?"}; el.innerHTML = symbols[type] || symbols.sparkle; el.className = "emotion-overlay " + type + " show"; window.setTimeout(function () { el.className = "emotion-overlay"; }, 1200); } function autonomousStep() { if (titleOpen || eggOpen || hatchInYard || statusOpen || submenu || state.expression === "sleep" || state.started === false) { return; } var roll = Math.random(); if (roll < .22) { react("wiggle"); showEmotion("curious"); } else if (roll < .38 && state.happiness > 60) { react("bounce"); showEmotion("sparkle"); } else if (roll < .48 && state.happiness < 32) { showEmotion("tears"); } }
  function generalState() { if (state.poop >= 55 || state.dirt >= 55) { return "precisando de limpeza"; } if (state.health < 42) { return "precisando de cuidado"; } if (state.energy < 22) { return "cansado"; } if (state.hunger < 22) { return "com fome"; } if (state.hygiene < 22) { return "precisando de banho"; } if (state.happiness < 30) { return "quietinho"; } if (state.happiness > 78 && state.hunger > 42 && state.energy > 35) { return "muito feliz"; } return "calmo"; }
  function personalityLabel() { var p = state.personality || {carinhoso:0, curioso:0, brincalhao:0}; if (p.carinhoso >= p.curioso && p.carinhoso >= p.brincalhao) { return "carinhoso"; } if (p.brincalhao >= p.curioso) { return "brincalhÃ£o"; } return "curioso"; }
  function mood() { if (state.poop >= 55 || state.dirt >= 55) { return "precisando de limpeza"; } if (state.health < 42) { return "precisando de cuidado"; } if (state.energy < 22) { return "cansado"; } if (state.hunger < 22) { return "com fome"; } if (state.hygiene < 22) { return "precisando de banho"; } if (state.happiness < 30) { return "quietinho"; } if (state.happiness > 78 && state.hunger > 42 && state.energy > 35) { return "muito feliz"; } return "calmo"; }
  function renderMainMenu() { var html = ""; var i; for (i = 0; i < actions.length; i++) { html += '<button class="carousel-item' + (i === selected ? ' selected' : '') + '" data-index="' + i + '"><span class="ico">' + actions[i].icon + '</span>' + actions[i].label + '</button>'; } var track = document.getElementById("carousel-track"); if (!track) { return; } track.innerHTML = html; var items = track.getElementsByTagName("button"); for (i = 0; i < items.length; i++) { items[i].onclick = function () { selected = parseInt(this.getAttribute("data-index"), 10); renderMainMenu(); }; } }
  function renderSubmenu() { var strip = document.getElementById("submenu-strip"); var track = document.getElementById("submenu-track"); if (!strip || !track) { return; } if (!submenu) { track.innerHTML = ""; strip.className = "submenu-strip menu-hidden"; return; } var list = submenuItems(); var html = ""; var i; for (i = 0; i < list.length; i++) { html += '<button class="submenu-item' + (i === submenuSelected ? ' selected' : '') + '" data-index="' + i + '">' + list[i].label + '</button>'; } track.innerHTML = html; strip.className = menuOpen ? "submenu-strip" : "submenu-strip menu-hidden"; var items = track.getElementsByTagName("button"); for (i = 0; i < items.length; i++) { items[i].onclick = function () { submenuSelected = parseInt(this.getAttribute("data-index"), 10); select(); }; } }
  function renderCarousel() { renderMainMenu(); renderSubmenu(); }
  function bar(id, v) { document.getElementById(id).style.width = v + "%"; document.getElementById(id + "-text").innerHTML = Math.round(v) + "%"; }
  function render() { updateDayNight(); var t = now(); document.getElementById("screen-time").innerHTML = t; document.getElementById("footer-time").innerHTML = t; document.getElementById("screen-stage").innerHTML = state.stage.toUpperCase() + " Â· NV." + (state.level || 1) + " Â· " + state.name.toUpperCase(); document.getElementById("status-name").innerHTML = state.name; document.getElementById("status-species").innerHTML = state.species; document.getElementById("status-stage").innerHTML = state.stage; document.getElementById("status-bond").innerHTML = state.bond; document.getElementById("status-care").innerHTML = state.care; document.getElementById("status-memories").innerHTML = state.memories.length; document.getElementById("status-memory").innerHTML = "Última memória: " + (state.memories[0] || "ainda não há memórias."); document.getElementById("status-general").innerHTML = "Estado geral: " + generalState(); document.getElementById("status-profile").innerHTML = "NÃ­vel " + (state.level || 1) + " Â· XP " + (state.xp || 0) + " Â· Personalidade: " + personalityLabel() + " Â· Rotina: " + ((state.routine && state.routine.streak) || 0) + " dia(s)"; bar("status-hunger", state.hunger); bar("status-energy", state.energy); bar("status-happiness", state.happiness); bar("status-hygiene", state.hygiene); bar("status-health", state.health); var dirtMark = document.getElementById("dirt-mark"); if (dirtMark) { if (state.poop >= 45) { dirtMark.className = "dirt-mark visible poop"; } else if (state.dirt >= 20) { dirtMark.className = "dirt-mark visible"; } else { dirtMark.className = "dirt-mark"; } } var asset = document.getElementById("pet-asset"); if (asset) { asset.style.transform = "scale(" + growthScale() + ")"; } if (asset && !animationTimer) { asset.src = "assets/" + assetFolder() + "/" + assetExpression() + ".png"; } }
  function openStatus() { submenu = null; submenuSelected = 0; statusOpen = true; document.getElementById("home-view").style.display = "none"; document.getElementById("status-view").style.display = "block"; render(); }
  function closeStatus() { statusOpen = false; document.getElementById("status-view").style.display = "none"; document.getElementById("home-view").style.display = "block"; renderCarousel(); renderMenuState(); }
  function renderTitleMenu() { var items = document.getElementById("title-modal").getElementsByTagName("button"); var i; for (i = 0; i < items.length; i++) { items[i].className = "title-menu" + (i === titleSelected ? " selected" : ""); } }
  function renderEggChoices() { var items = document.getElementById("egg-modal").getElementsByTagName("button"); var i; for (i = 0; i < items.length; i++) { var species = items[i].getAttribute("data-species"); if (species) { items[i].className = "egg-choice" + (eggSpecies[eggSelected] === species ? " selected" : ""); } } }
  function eggFile(species) { return species === "Fogo" ? "fire" : (species === "Planta" ? "plant" : "water"); }
  function startTitle() { titleOpen = false; document.getElementById("title-modal").style.display = "none"; if (state.started) { render(); playSequence("idle", true); toast("Bem-vindo de volta!"); return; } eggOpen = true; document.getElementById("egg-modal").style.display = "block"; renderEggChoices(); }
  function chooseEgg(species) { var i; for (i = 0; i < eggSpecies.length; i++) { if (eggSpecies[i] === species) { eggSelected = i; } } renderEggChoices(); }
  function selectTitle() { if (titleSelected === 0) { startTitle(); } else if (titleSelected === 1) { toast("Options estarão disponíveis em uma próxima versão."); } else { window.close(); } }
  function spawnParticles(kind) { var layer = document.getElementById("particle-layer"); if (!layer) { return; } var symbols = {clean:"âœ¦", pet:"â™¥", feed:"â—", play:"âœ¦", sleep:"z"}; var i; for (i = 0; i < 7; i++) { var p = document.createElement("span"); p.className = "particle " + (kind || "play"); p.innerHTML = symbols[kind] || "âœ¦"; p.style.left = (35 + Math.floor(Math.random() * 30)) + "%"; p.style.animationDelay = (i * 0.07) + "s"; layer.appendChild(p); (function (node) { window.setTimeout(function () { if (node && node.parentNode) { node.parentNode.removeChild(node); } }, 1900); })(p); } }
  function spawnHatchParticles(species) { var layer = document.getElementById("particle-layer"); if (!layer) { return; } var type = species === "Fogo" ? "fire" : (species === "Planta" ? "plant" : "water"); var i; for (i = 0; i < 16; i++) { var p = document.createElement("span"); p.className = "particle hatch " + type; p.innerHTML = i % 3 === 0 ? "âœ¦" : "â€¢"; p.style.left = (38 + Math.floor(Math.random() * 24)) + "%"; p.style.animationDelay = (i * 0.035) + "s"; layer.appendChild(p); (function (node) { window.setTimeout(function () { if (node && node.parentNode) { node.parentNode.removeChild(node); } }, 1250); })(p); } }
  function beginHatch() { var species = eggSpecies[eggSelected]; var file = eggFile(species); eggOpen = false; hatchInYard = true; document.getElementById("egg-modal").style.display = "none"; document.getElementById("hatch-modal").style.display = "none"; document.getElementById("hatch-yard-egg").src = "assets/eggs/" + file + ".png"; document.getElementById("hatch-yard-egg").style.display = "block"; document.getElementById("pet-placeholder").className = "pet-placeholder asset-mode hatching"; if (animationTimer) { window.clearTimeout(animationTimer); animationTimer = null; } animationToken++; if (hatchTimer) { window.clearTimeout(hatchTimer); } hatchTimer = window.setTimeout(function () { spawnHatchParticles(species); document.getElementById("pet-placeholder").className = "pet-placeholder asset-mode hatching revealing"; hatchTimer = window.setTimeout(function () { finishHatch(species); }, 900); }, 5000); }
  function finishHatch(species) { if (hatchTimer) { window.clearTimeout(hatchTimer); hatchTimer = null; } hatchInYard = false; document.getElementById("pet-placeholder").className = "pet-placeholder asset-mode"; document.getElementById("hatch-yard-egg").style.display = "none"; state = newPet("Kyu", species); state.started = true; save(); render(); playSequence("idle", true); toast("Seu primeiro MiniKyumon chegou!"); }
  function move(dir) { if (hatchInYard) { return; } if (titleOpen) { titleSelected += dir; if (titleSelected < 0) { titleSelected = 2; } if (titleSelected > 2) { titleSelected = 0; } renderTitleMenu(); return; } if (eggOpen) { eggSelected += dir; if (eggSelected < 0) { eggSelected = 2; } if (eggSelected > 2) { eggSelected = 0; } renderEggChoices(); return; } if (statusOpen || !menuOpen) { return; } if (submenu) { submenuSelected += dir; if (submenuSelected < 0) { submenuSelected = submenuItems().length - 1; } if (submenuSelected >= submenuItems().length) { submenuSelected = 0; } renderCarousel(); return; } selected += dir; if (selected < 0) { selected = actions.length - 1; } if (selected >= actions.length) { selected = 0; } renderCarousel(); parallaxShift(dir); }
  function select() { if (hatchInYard) { return; } if (titleOpen) { selectTitle(); return; } if (eggOpen) { beginHatch(); return; } if (!statusOpen && menuOpen) { if (submenu) { var option = submenuItems()[submenuSelected]; if (submenu === "feed") { performFeed(option.id); } else if (submenu === "play") { performPlay(option.id); } else { performSleep(option.id); } } else { action(actions[selected].id); } } }
  function renderMenuState() { var menu = document.getElementById("carousel"); var sub = document.getElementById("submenu-strip"); if (menu) { menu.className = menuOpen ? "carousel" : "carousel menu-hidden"; } if (sub) { sub.className = (menuOpen && submenu) ? "submenu-strip" : "submenu-strip menu-hidden"; } }
  function backAction() { if (hatchInYard || titleOpen || eggOpen || statusOpen) { return false; } var modal = document.getElementById("new-pet-modal"); if (modal && modal.style.display === "block") { modal.style.display = "none"; toast("AÃ§Ã£o cancelada."); return false; } if (submenu) { submenu = null; submenuSelected = 0; menuOpen = true; renderCarousel(); renderMenuState(); toast("Menu principal."); return false; } if (menuOpen) { menuOpen = false; renderMenuState(); toast("Menu recolhido."); return false; } menuOpen = true; renderMenuState(); toast("Menu aberto."); return false; }
  function yellowButtonAction(e) { e = e || window.event; if (e) { e.returnValue = false; e.cancelBubble = true; } return backAction(); }
  function toggleMenu() { if (hatchInYard) { return; } if (submenu) { submenu = null; submenuSelected = 0; renderCarousel(); toast("Menu principal."); return; } var modal = document.getElementById("new-pet-modal"); if (modal.style.display === "block") { modal.style.display = "none"; toast("Ação cancelada."); return; } if (eggOpen) { eggOpen = false; titleOpen = true; document.getElementById("egg-modal").style.display = "none"; document.getElementById("title-modal").style.display = "block"; renderTitleMenu(); return; } if (titleOpen || statusOpen) { return; } menuOpen = !menuOpen; renderMenuState(); toast(menuOpen ? "Menu aberto." : "Menu recolhido."); }
  function bounce() { var el = document.getElementById("pet-placeholder"); el.className = "pet-placeholder bounce"; window.setTimeout(function () { el.className = "pet-placeholder"; }, 500); }
  function toast(text) { var el = document.getElementById("toast"); el.innerHTML = text; el.style.display = "block"; if (toastTimer) { window.clearTimeout(toastTimer); } toastTimer = window.setTimeout(function () { el.style.display = "none"; }, 1700); }
  function cancelOrBack() { var modal = document.getElementById("new-pet-modal"); if (modal.style.display === "block") { modal.style.display = "none"; toast("Ação cancelada."); } else if (statusOpen) { closeStatus(); } else { toast("Você já está na tela principal."); } }
  function openNew() { document.getElementById("new-pet-modal").style.display = "block"; } function chooseIntroSpecies(species) { introSpecies = species; var choices = document.getElementById("intro-modal").getElementsByTagName("button"); var i; for (i = 0; i < choices.length; i++) { if (choices[i].getAttribute("data-species") === species) { choices[i].className = "species-choice selected"; } else if (choices[i].getAttribute("data-species")) { choices[i].className = "species-choice"; } } } function startIntro() { var name = document.getElementById("intro-name-input").value.replace(/^\s+|\s+$/g, ""); if (!name) { name = "Kyu"; } state = newPet(name, introSpecies); introOpen = false; document.getElementById("intro-modal").style.display = "none"; save(); render(); playSequence("idle", true); toast("Seu primeiro MiniKyumon chegou!"); }
  function confirmNew() { var name = document.getElementById("pet-name-input").value.replace(/^\s+|\s+$/g, ""); if (!name) { name = "Kyu"; } state = newPet(name, document.getElementById("species-input").value); state.started = true; document.getElementById("new-pet-modal").style.display = "none"; if (animationTimer) { window.clearTimeout(animationTimer); animationTimer = null; } animationToken++; save(); render(); playSequence("idle", true); toast("Ovo chocado. Nova rotina iniciada!"); }
  function updateDayNight() { var el = document.getElementById("yard-background"); if (!el) { return; } var h = new Date().getHours(); var file = (h >= 6 && h < 12) ? "manha.png" : ((h >= 12 && h < 18) ? "tarde.png" : "noite.png"); el.style.backgroundImage = "url('assets/yard/" + file + "')"; el.setAttribute("data-period", file.replace(".png", "")); }
  function tick() { updateDayNight(); var t = new Date().getTime(); var mins = (t - lastTick) / 60000; if (mins >= 1 && state.started !== false) { var f = Math.min(mins, 10); state.hunger = clamp(state.hunger - f * .06); state.energy = clamp(state.energy - f * .0367); state.happiness = clamp(state.happiness - f * .0267); state.hygiene = clamp(state.hygiene - f * .0333); state.dirt = clamp(state.dirt + f * .0058); var balance = Math.min(state.hunger, state.energy, state.happiness, state.hygiene); if (balance > 48) { state.health = clamp(state.health + f * .0075); } else if (balance < 18) { state.health = clamp(state.health - f * .0025); } lastTick = t; save(); render(); } document.getElementById("screen-time").innerHTML = now(); document.getElementById("footer-time").innerHTML = now(); }
  function scaleConsoleProportionally() {
    var shell = document.querySelector(".shell");
    if (!shell) { return; }
    var w = document.documentElement.clientWidth || window.innerWidth || 585;
    var h = document.documentElement.clientHeight || window.innerHeight || 427;
    var scale = Math.min(w / 585, h / 427);
    if (!isFinite(scale) || scale < 1) { scale = 1; }
    shell.style.transform = "translate(-50%, -50%) scale(" + scale.toFixed(4) + ")";
  }
  function wire() { var titleChoices = document.getElementById("title-modal").getElementsByTagName("button"); var ti; for (ti = 0; ti < titleChoices.length; ti++) { titleChoices[ti].onclick = function () { titleSelected = this.getAttribute("data-title") === "start" ? 0 : (this.getAttribute("data-title") === "options" ? 1 : 2); renderTitleMenu(); selectTitle(); }; } var eggChoices = document.getElementById("egg-modal").getElementsByTagName("button"); var ei; for (ei = 0; ei < eggChoices.length; ei++) { if (eggChoices[ei].getAttribute("data-species")) { eggChoices[ei].onclick = function () { chooseEgg(this.getAttribute("data-species")); }; } } document.getElementById("egg-back").onclick = toggleMenu; document.getElementById("carousel-left").onclick = function () { move(-1); }; document.getElementById("carousel-right").onclick = function () { move(1); }; document.getElementById("dpad-left").onclick = function () { move(-1); }; document.getElementById("dpad-right").onclick = function () { move(1); }; document.getElementById("dpad-up").onclick = function () { move(-1); }; document.getElementById("dpad-down").onclick = function () { move(1); }; document.getElementById("green-button").onclick = select; document.getElementById("yellow-button").onclick = yellowButtonAction; document.getElementById("pink-button").onclick = function () { if (titleOpen || eggOpen || hatchInYard || document.getElementById("hatch-modal").style.display === "block") { return; } if (statusOpen) { closeStatus(); } else { openStatus(); } }; document.getElementById("back-status").onclick = closeStatus; document.getElementById("cancel-new").onclick = function () { document.getElementById("new-pet-modal").style.display = "none"; }; document.getElementById("confirm-new").onclick = confirmNew; document.onkeydown = function (e) { e = e || window.event; var key = e.keyCode; if (key === 37 || key === 38) { move(-1); } else if (key === 39 || key === 40) { move(1); } else if (key === 13 || key === 32) { select(); } else if (key === 83) { if (statusOpen) { closeStatus(); } else { openStatus(); } } else if (key === 27 || key === 88) { backAction(); } }; }
  try { window.resizeTo(585, 427); window.moveTo(0, 0); } catch (e) {}
  load(); wire(); window.onresize = scaleConsoleProportionally; scaleConsoleProportionally(); renderCarousel(); renderMenuState(); applyTimeOfDay(); render(); if (titleOpen) { document.getElementById("title-modal").style.display = "block"; renderTitleMenu(); } window.setInterval(tick, 10000); window.setInterval(idleStep, 420); autonomousTimer = window.setInterval(autonomousStep, 6500);
}());